### ISSUE TITLE
How to make this work with jacoco in bitbucket

### ISSUE THREAD

**Issue by preritsarvaiya** [LoremFooBar/reportgenerator-coverage-bitbucket-pipe#2]
I am encountering difficulties while working with the provided example, as it does not seem to function properly in Java. Could you please share the appropriate documentation related to this?

Error:
`2023-07-12T06:09:09: The report file pattern '**/coverage*.xml' found no matching files.
2023-07-12T06:09:09: No report files specified.
Unhandled exception. ReportGenerator.BitbucketPipe.ReportGenerationFailedException: Exception of type 'ReportGenerator.BitbucketPipe.ReportGenerationFailedException' was thrown.
   at ReportGenerator.BitbucketPipe.CoverageReportGenerator.GenerateCoverageReportAsync() in /source/CoverageReportGenerator.cs:line 39
   at ReportGenerator.BitbucketPipe.PipeRunner.RunPipeAsync() in /source/PipeRunner.cs:line 29
   at ReportGenerator.BitbucketPipe.Program.Main() in /source/Program.cs:line 20
   at ReportGenerator.BitbucketPipe.Program.<Main>()
`

This is the pipeline i am using
`pipelines:
  default:
    - step:
        name: Build and Test
        image: maven:3.8.3-openjdk-17-slim
        script:
          - mvn clean install
          - mvn jacoco:report
        artifacts:
          - target/site/jacoco/**

    - step:
        name: Generate Code Coverage Report
        image: mcr.microsoft.com/dotnet/core/sdk:3.1
        script:
          - dotnet tool update dotnet-reportgenerator-globaltool --tool-path tools --version 5.1.23
          - tools/reportgenerator -reports:target/site/jacoco/jacoco.xml -targetdir:coveragereport -reporttypes:Html
        artifacts:
          - coveragereport/**

    - step:
        name: Publish Code Coverage Report
        script:
          - pipe: docker://loremfoobar/reportgenerator-coverage-bitbucket-pipe:0.8.0
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_USERNAME
              BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
              LINE_COVERAGE_MINIMUM: "80"
              BRANCH_COVERAGE_MINIMUM: "80"`

**Comment by LoremFooBar** [comment]
You should add the `REPORTS` variable if the path of the report(s) is different than the default. In your case it could be `target/site/jacoco/jacoco.xml`, or you can use globbing if you expect more than one report to be produced.

**Comment by preritsarvaiya** [comment]
So will be adding that. Can you provide me an example?
