### ISSUE TITLE
Update to ReportGenerator.Core Version 5.2.0

### ISSUE THREAD

**Issue by tvbishan** [LoremFooBar/reportgenerator-coverage-bitbucket-pipe#4]
It seems like current release is using the ReportGenerator.Core version 5.1.24. It is better to update to ReportGenerator.Core version 5.2.0

**Comment by LoremFooBar** [comment]
I checked the release notes for ReportGenerator 5.2.0, it doesn't seem like any of the changes could affect usage of this pipe. Did you encounter any issues that could be resolved with this update?

**Comment by tvbishan** [comment]
I haven't had any problems with the current version. I thought the changes like Improved support for local methods (Cobertura, dotCover, OpenCover, VisualStudio), Visual Studio Coverage: Added support for partial line coverage and etc.. would improve the result.

**Comment by LoremFooBar** [comment]
I misread the release notes for ReportGenerator, I thought the improvements were related to Visual Studio itself. My bad. Released v0.8.1 with updated ReportGenerator package.

**Comment by tvbishan** [comment]
Sorry Again.

Any idea to update to ReportGenerator.Core version 5.2.1 which has  'Crap Score' metric for Coberatura coverage files.

https://github.com/danielpalme/ReportGenerator/releases/tag/v5.2.1

**Comment by LoremFooBar** [comment]
Released 0.8.2 with ReportGenerator 5.2.1.
