### ISSUE TITLE
Possibility to support diff coverage - Html report

### ISSUE THREAD

**Issue by tvbishan** [LoremFooBar/reportgenerator-coverage-bitbucket-pipe#5]
Would it be feasible to count coverage for modifications made to the code (including those made or added) instead of the overall code?

Currently, I'm generating Html report and it shows the coverage gets measured for the entire codebase of the project. But, in the context of pull requests, I need to see if the specific lines of code that were added or changed are covered (diff coverage).

I am aware that TextDeltaSummary exists. But is there a way to see the Diff Coverage in the HTML report instead of the Full Coverage?

**Comment by LoremFooBar** [comment]
The pipe uses `ReportGenerator` to generate a readable coverage report based on coverage data that is collected before the pipe is running. If you can collect code coverage based on changed lines/files only, you can use it as input to the pipe and it should generate a report that reflects that input. 

Another option I can think of is to add an option to the pipe that adds annotations to the PR on lines that are not covered. I am not 100 percent sure how viable that option is. I also don't think I can add this feature anytime soon.
